-- Class 5–8 NCERT chapter list + one practice activity per chapter.
-- Question banks live in src/data/activities (PracticeEngine). This seed
-- only registers chapters and games_catalog rows so stars/XP work the
-- same way as Batch 1 games. Activities are ordered by chapter_num.

insert into public.curriculum_chapters (class_num, subject, chapter_num, chapter_ref, title) values
  (5, 'English', 1, 'c5-eng-01', 'Ice-cream Man / Wonderful Waste!'),
  (5, 'English', 2, 'c5-eng-02', 'Teamwork / Flying Together'),
  (5, 'English', 3, 'c5-eng-03', 'My Shadow / Robinson Crusoe'),
  (5, 'English', 4, 'c5-eng-04', 'Crying / My Elder Brother'),
  (5, 'English', 5, 'c5-eng-05', 'Rip Van Winkle'),
  (5, 'English', 6, 'c5-eng-06', 'Class Discussion / The Talkative Barber'),
  (5, 'English', 7, 'c5-eng-07', 'Topsy-turvy Land / Gulliver''s Travels'),
  (5, 'English', 8, 'c5-eng-08', 'Nobody''s Friend / The Little Bully'),
  (5, 'English', 9, 'c5-eng-09', 'Sing a Song of People / Around the World'),
  (5, 'English', 10, 'c5-eng-10', 'Malu Bhalu / Who Will be Ningthou?'),
  (5, 'English', 11, 'c5-eng-11', 'Reading Comprehension'),
  (5, 'English', 12, 'c5-eng-12', 'Grammar in Context'),
  (5, 'English', 13, 'c5-eng-13', 'Vocabulary Building'),
  (5, 'English', 14, 'c5-eng-14', 'Functional Writing'),
  (5, 'Mathematics', 1, 'c5-math-01', 'The Fish Tale'),
  (5, 'Mathematics', 2, 'c5-math-02', 'Shapes and Angles'),
  (5, 'Mathematics', 3, 'c5-math-03', 'How Many Squares?'),
  (5, 'Mathematics', 4, 'c5-math-04', 'Parts and Wholes'),
  (5, 'Mathematics', 5, 'c5-math-05', 'Does it Look the Same?'),
  (5, 'Mathematics', 6, 'c5-math-06', 'Be My Multiple, I''ll be Your Factor'),
  (5, 'Mathematics', 7, 'c5-math-07', 'Can You See the Pattern?'),
  (5, 'Mathematics', 8, 'c5-math-08', 'Mapping Your Way'),
  (5, 'Mathematics', 9, 'c5-math-09', 'Boxes and Sketches'),
  (5, 'Mathematics', 10, 'c5-math-10', 'Tenths and Hundredths'),
  (5, 'Mathematics', 11, 'c5-math-11', 'Area and its Boundary'),
  (5, 'Mathematics', 12, 'c5-math-12', 'Smart Charts'),
  (5, 'Mathematics', 13, 'c5-math-13', 'Ways to Multiply and Divide'),
  (5, 'Mathematics', 14, 'c5-math-14', 'How Big? How Heavy?'),
  (5, 'World Around Us', 1, 'c5-wau-01', 'Super Senses'),
  (5, 'World Around Us', 2, 'c5-wau-02', 'A Snake Charmer''s Story'),
  (5, 'World Around Us', 3, 'c5-wau-03', 'From Tasting to Digesting'),
  (5, 'World Around Us', 4, 'c5-wau-04', 'Mangoes Round the Year'),
  (5, 'World Around Us', 5, 'c5-wau-05', 'Seeds and Seeds'),
  (5, 'World Around Us', 6, 'c5-wau-06', 'Every Drop Counts'),
  (5, 'World Around Us', 7, 'c5-wau-07', 'Experiments with Water'),
  (5, 'World Around Us', 8, 'c5-wau-08', 'A Treat for Mosquitoes'),
  (5, 'World Around Us', 9, 'c5-wau-09', 'Up You Go!'),
  (5, 'World Around Us', 10, 'c5-wau-10', 'Walls Tell Stories'),
  (5, 'World Around Us', 11, 'c5-wau-11', 'Sunita in Space'),
  (5, 'World Around Us', 12, 'c5-wau-12', 'What if it Finishes...?'),
  (5, 'World Around Us', 13, 'c5-wau-13', 'A Shelter so High!'),
  (5, 'World Around Us', 14, 'c5-wau-14', 'When the Earth Shook!'),
  (5, 'World Around Us', 15, 'c5-wau-15', 'Blow Hot, Blow Cold'),
  (5, 'World Around Us', 16, 'c5-wau-16', 'Who will do this Work?'),
  (5, 'World Around Us', 17, 'c5-wau-17', 'Across the Wall'),
  (5, 'World Around Us', 18, 'c5-wau-18', 'No Place for Us?'),
  (5, 'World Around Us', 19, 'c5-wau-19', 'A Seed Tells a Farmer''s Story'),
  (5, 'World Around Us', 20, 'c5-wau-20', 'Whose Forests?'),
  (5, 'World Around Us', 21, 'c5-wau-21', 'Like Father, Like Daughter'),
  (5, 'World Around Us', 22, 'c5-wau-22', 'On the Move Again'),
  (6, 'English', 1, 'c6-eng-01', 'Who Did Patrick''s Homework?'),
  (6, 'English', 2, 'c6-eng-02', 'How the Dog Found Himself a New Master!'),
  (6, 'English', 3, 'c6-eng-03', 'Taro''s Reward'),
  (6, 'English', 4, 'c6-eng-04', 'An Indian-American Woman in Space'),
  (6, 'English', 5, 'c6-eng-05', 'A Different Kind of School'),
  (6, 'English', 6, 'c6-eng-06', 'Who I Am'),
  (6, 'English', 7, 'c6-eng-07', 'Fair Play'),
  (6, 'English', 8, 'c6-eng-08', 'A Game of Chance'),
  (6, 'English', 9, 'c6-eng-09', 'Desert Animals'),
  (6, 'English', 10, 'c6-eng-10', 'The Banyan Tree'),
  (6, 'English', 11, 'c6-eng-11', 'Grammar in Context'),
  (6, 'English', 12, 'c6-eng-12', 'Reading Comprehension'),
  (6, 'English', 13, 'c6-eng-13', 'Functional Writing'),
  (6, 'Mathematics', 1, 'c6-math-01', 'Knowing Our Numbers'),
  (6, 'Mathematics', 2, 'c6-math-02', 'Whole Numbers'),
  (6, 'Mathematics', 3, 'c6-math-03', 'Playing with Numbers'),
  (6, 'Mathematics', 4, 'c6-math-04', 'Basic Geometrical Ideas'),
  (6, 'Mathematics', 5, 'c6-math-05', 'Understanding Elementary Shapes'),
  (6, 'Mathematics', 6, 'c6-math-06', 'Integers'),
  (6, 'Mathematics', 7, 'c6-math-07', 'Fractions'),
  (6, 'Mathematics', 8, 'c6-math-08', 'Decimals'),
  (6, 'Mathematics', 9, 'c6-math-09', 'Data Handling'),
  (6, 'Mathematics', 10, 'c6-math-10', 'Mensuration'),
  (6, 'Mathematics', 11, 'c6-math-11', 'Algebra'),
  (6, 'Mathematics', 12, 'c6-math-12', 'Ratio and Proportion'),
  (6, 'Mathematics', 13, 'c6-math-13', 'Symmetry'),
  (6, 'Mathematics', 14, 'c6-math-14', 'Practical Geometry'),
  (6, 'Science', 1, 'c6-sci-01', 'Components of Food'),
  (6, 'Science', 2, 'c6-sci-02', 'Sorting Materials into Groups'),
  (6, 'Science', 3, 'c6-sci-03', 'Separation of Substances'),
  (6, 'Science', 4, 'c6-sci-04', 'Getting to Know Plants'),
  (6, 'Science', 5, 'c6-sci-05', 'Body Movements'),
  (6, 'Science', 6, 'c6-sci-06', 'Motion and Measurement of Distances'),
  (6, 'Science', 7, 'c6-sci-07', 'The Living Organisms — Characteristics and Habitats'),
  (6, 'Science', 8, 'c6-sci-08', 'Water'),
  (6, 'Science', 9, 'c6-sci-09', 'Light, Shadows and Reflections'),
  (6, 'Science', 10, 'c6-sci-10', 'Electricity and Circuits'),
  (6, 'Science', 11, 'c6-sci-11', 'Fun with Magnets'),
  (6, 'Science', 12, 'c6-sci-12', 'Air Around Us'),
  (6, 'Science', 13, 'c6-sci-13', 'Garbage In, Garbage Out'),
  (6, 'Social Science', 1, 'c6-sst-01', 'What, Where, How and When? (History)'),
  (6, 'Social Science', 2, 'c6-sst-02', 'From Gathering to Growing Food (History)'),
  (6, 'Social Science', 3, 'c6-sst-03', 'In the Earliest Cities (History)'),
  (6, 'Social Science', 4, 'c6-sst-04', 'What Books and Burials Tell Us (History)'),
  (6, 'Social Science', 5, 'c6-sst-05', 'Kingdoms, Kings and an Early Republic (History)'),
  (6, 'Social Science', 6, 'c6-sst-06', 'New Questions and Ideas (History)'),
  (6, 'Social Science', 7, 'c6-sst-07', 'Ashoka, The Emperor Who Gave Up War (History)'),
  (6, 'Social Science', 8, 'c6-sst-08', 'Vital Villages, Thriving Towns (History)'),
  (6, 'Social Science', 9, 'c6-sst-09', 'Traders, Kings and Pilgrims (History)'),
  (6, 'Social Science', 10, 'c6-sst-10', 'New Empires and Kingdoms (History)'),
  (6, 'Social Science', 11, 'c6-sst-11', 'Buildings, Paintings and Books (History)'),
  (6, 'Social Science', 12, 'c6-sst-12', 'The Earth in the Solar System (Geography)'),
  (6, 'Social Science', 13, 'c6-sst-13', 'Globe: Latitudes and Longitudes (Geography)'),
  (6, 'Social Science', 14, 'c6-sst-14', 'Motions of the Earth (Geography)'),
  (6, 'Social Science', 15, 'c6-sst-15', 'Maps (Geography)'),
  (6, 'Social Science', 16, 'c6-sst-16', 'Major Domains of the Earth (Geography)'),
  (6, 'Social Science', 17, 'c6-sst-17', 'Major Landforms of the Earth (Geography)'),
  (6, 'Social Science', 18, 'c6-sst-18', 'Our Country — India (Geography)'),
  (6, 'Social Science', 19, 'c6-sst-19', 'India: Climate, Vegetation and Wildlife (Geography)'),
  (6, 'Social Science', 20, 'c6-sst-20', 'Understanding Diversity (Civics)'),
  (6, 'Social Science', 21, 'c6-sst-21', 'Diversity and Discrimination (Civics)'),
  (6, 'Social Science', 22, 'c6-sst-22', 'What is Government? (Civics)'),
  (6, 'Social Science', 23, 'c6-sst-23', 'Key Elements of a Democratic Government (Civics)'),
  (6, 'Social Science', 24, 'c6-sst-24', 'Panchayati Raj (Civics)'),
  (6, 'Social Science', 25, 'c6-sst-25', 'Rural Administration (Civics)'),
  (6, 'Social Science', 26, 'c6-sst-26', 'Urban Administration (Civics)'),
  (6, 'Social Science', 27, 'c6-sst-27', 'Rural Livelihoods (Civics)'),
  (6, 'Social Science', 28, 'c6-sst-28', 'Urban Livelihoods (Civics)'),
  (7, 'English', 1, 'c7-eng-01', 'Three Questions'),
  (7, 'English', 2, 'c7-eng-02', 'A Gift of Chappals'),
  (7, 'English', 3, 'c7-eng-03', 'Gopal and the Hilsa Fish'),
  (7, 'English', 4, 'c7-eng-04', 'The Ashes that Made Trees Bloom'),
  (7, 'English', 5, 'c7-eng-05', 'Quality'),
  (7, 'English', 6, 'c7-eng-06', 'Expert Detectives'),
  (7, 'English', 7, 'c7-eng-07', 'The Invention of Vita-Wonk'),
  (7, 'English', 8, 'c7-eng-08', 'Fire: Friend and Foe'),
  (7, 'English', 9, 'c7-eng-09', 'A Bicycle in Good Repair'),
  (7, 'English', 10, 'c7-eng-10', 'The Story of Cricket'),
  (7, 'English', 11, 'c7-eng-11', 'Grammar in Context'),
  (7, 'English', 12, 'c7-eng-12', 'Reading Comprehension'),
  (7, 'Mathematics', 1, 'c7-math-01', 'Integers'),
  (7, 'Mathematics', 2, 'c7-math-02', 'Fractions and Decimals'),
  (7, 'Mathematics', 3, 'c7-math-03', 'Data Handling'),
  (7, 'Mathematics', 4, 'c7-math-04', 'Simple Equations'),
  (7, 'Mathematics', 5, 'c7-math-05', 'Lines and Angles'),
  (7, 'Mathematics', 6, 'c7-math-06', 'The Triangle and its Properties'),
  (7, 'Mathematics', 7, 'c7-math-07', 'Congruence of Triangles'),
  (7, 'Mathematics', 8, 'c7-math-08', 'Comparing Quantities'),
  (7, 'Mathematics', 9, 'c7-math-09', 'Rational Numbers'),
  (7, 'Mathematics', 10, 'c7-math-10', 'Practical Geometry'),
  (7, 'Mathematics', 11, 'c7-math-11', 'Perimeter and Area'),
  (7, 'Mathematics', 12, 'c7-math-12', 'Algebraic Expressions'),
  (7, 'Mathematics', 13, 'c7-math-13', 'Exponents and Powers'),
  (7, 'Mathematics', 14, 'c7-math-14', 'Symmetry'),
  (7, 'Mathematics', 15, 'c7-math-15', 'Visualising Solid Shapes'),
  (7, 'Science', 1, 'c7-sci-01', 'Nutrition in Plants'),
  (7, 'Science', 2, 'c7-sci-02', 'Nutrition in Animals'),
  (7, 'Science', 3, 'c7-sci-03', 'Fibre to Fabric'),
  (7, 'Science', 4, 'c7-sci-04', 'Heat'),
  (7, 'Science', 5, 'c7-sci-05', 'Acids, Bases and Salts'),
  (7, 'Science', 6, 'c7-sci-06', 'Physical and Chemical Changes'),
  (7, 'Science', 7, 'c7-sci-07', 'Weather, Climate and Adaptations of Animals to Climate'),
  (7, 'Science', 8, 'c7-sci-08', 'Winds, Storms and Cyclones'),
  (7, 'Science', 9, 'c7-sci-09', 'Soil'),
  (7, 'Science', 10, 'c7-sci-10', 'Respiration in Organisms'),
  (7, 'Science', 11, 'c7-sci-11', 'Transportation in Animals and Plants'),
  (7, 'Science', 12, 'c7-sci-12', 'Reproduction in Plants'),
  (7, 'Science', 13, 'c7-sci-13', 'Motion and Time'),
  (7, 'Science', 14, 'c7-sci-14', 'Electric Current and Its Effects'),
  (7, 'Science', 15, 'c7-sci-15', 'Light'),
  (7, 'Science', 16, 'c7-sci-16', 'Water: A Precious Resource'),
  (7, 'Science', 17, 'c7-sci-17', 'Forests: Our Lifeline'),
  (7, 'Science', 18, 'c7-sci-18', 'Wastewater Story'),
  (7, 'Social Science', 1, 'c7-sst-01', 'Tracing Changes Through a Thousand Years (History)'),
  (7, 'Social Science', 2, 'c7-sst-02', 'New Kings and Kingdoms (History)'),
  (7, 'Social Science', 3, 'c7-sst-03', 'The Delhi Sultans (History)'),
  (7, 'Social Science', 4, 'c7-sst-04', 'The Mughal Empire (History)'),
  (7, 'Social Science', 5, 'c7-sst-05', 'Rulers and Buildings (History)'),
  (7, 'Social Science', 6, 'c7-sst-06', 'Towns, Traders and Craftspersons (History)'),
  (7, 'Social Science', 7, 'c7-sst-07', 'Tribes, Nomads and Settled Communities (History)'),
  (7, 'Social Science', 8, 'c7-sst-08', 'Devotional Paths to the Divine (History)'),
  (7, 'Social Science', 9, 'c7-sst-09', 'The Making of Regional Cultures (History)'),
  (7, 'Social Science', 10, 'c7-sst-10', 'Eighteenth-Century Political Formations (History)'),
  (7, 'Social Science', 11, 'c7-sst-11', 'Environment (Geography)'),
  (7, 'Social Science', 12, 'c7-sst-12', 'Inside Our Earth (Geography)'),
  (7, 'Social Science', 13, 'c7-sst-13', 'Our Changing Earth (Geography)'),
  (7, 'Social Science', 14, 'c7-sst-14', 'Air (Geography)'),
  (7, 'Social Science', 15, 'c7-sst-15', 'Water (Geography)'),
  (7, 'Social Science', 16, 'c7-sst-16', 'Natural Vegetation and Wildlife (Geography)'),
  (7, 'Social Science', 17, 'c7-sst-17', 'Human Environment – Settlement, Transport and Communication (Geography)'),
  (7, 'Social Science', 18, 'c7-sst-18', 'Human Environment Interactions – The Tropical and the Subtropical Region (Geography)'),
  (7, 'Social Science', 19, 'c7-sst-19', 'Life in the Deserts (Geography)'),
  (7, 'Social Science', 20, 'c7-sst-20', 'On Equality (Civics)'),
  (7, 'Social Science', 21, 'c7-sst-21', 'Role of the Government in Health (Civics)'),
  (7, 'Social Science', 22, 'c7-sst-22', 'How the State Government Works (Civics)'),
  (7, 'Social Science', 23, 'c7-sst-23', 'Growing up as Boys and Girls (Civics)'),
  (7, 'Social Science', 24, 'c7-sst-24', 'Women Change the World (Civics)'),
  (7, 'Social Science', 25, 'c7-sst-25', 'Understanding Media (Civics)'),
  (7, 'Social Science', 26, 'c7-sst-26', 'Markets Around Us (Civics)'),
  (7, 'Social Science', 27, 'c7-sst-27', 'A Shirt in the Market (Civics)'),
  (7, 'Social Science', 28, 'c7-sst-28', 'Struggles for Equality (Civics)'),
  (8, 'English', 1, 'c8-eng-01', 'The Best Christmas Present in the World'),
  (8, 'English', 2, 'c8-eng-02', 'The Tsunami'),
  (8, 'English', 3, 'c8-eng-03', 'Glimpses of the Past'),
  (8, 'English', 4, 'c8-eng-04', 'Bepin Choudhury’s Lapse of Memory'),
  (8, 'English', 5, 'c8-eng-05', 'The Summit Within'),
  (8, 'English', 6, 'c8-eng-06', 'This is Jody’s Fawn'),
  (8, 'English', 7, 'c8-eng-07', 'A Visit to Cambridge'),
  (8, 'English', 8, 'c8-eng-08', 'A Short Monsoon Diary'),
  (8, 'English', 9, 'c8-eng-09', 'The Great Stone Face – I & II'),
  (8, 'English', 10, 'c8-eng-10', 'Grammar: Reported Speech & Conditionals'),
  (8, 'English', 11, 'c8-eng-11', 'Analytical Reading'),
  (8, 'English', 12, 'c8-eng-12', 'Formal Writing'),
  (8, 'Mathematics', 1, 'c8-math-01', 'Rational Numbers'),
  (8, 'Mathematics', 2, 'c8-math-02', 'Linear Equations in One Variable'),
  (8, 'Mathematics', 3, 'c8-math-03', 'Understanding Quadrilaterals'),
  (8, 'Mathematics', 4, 'c8-math-04', 'Practical Geometry'),
  (8, 'Mathematics', 5, 'c8-math-05', 'Data Handling'),
  (8, 'Mathematics', 6, 'c8-math-06', 'Squares and Square Roots'),
  (8, 'Mathematics', 7, 'c8-math-07', 'Cubes and Cube Roots'),
  (8, 'Mathematics', 8, 'c8-math-08', 'Comparing Quantities'),
  (8, 'Mathematics', 9, 'c8-math-09', 'Algebraic Expressions and Identities'),
  (8, 'Mathematics', 10, 'c8-math-10', 'Visualising Solid Shapes'),
  (8, 'Mathematics', 11, 'c8-math-11', 'Mensuration'),
  (8, 'Mathematics', 12, 'c8-math-12', 'Exponents and Powers'),
  (8, 'Mathematics', 13, 'c8-math-13', 'Direct and Inverse Proportions'),
  (8, 'Mathematics', 14, 'c8-math-14', 'Factorisation'),
  (8, 'Mathematics', 15, 'c8-math-15', 'Introduction to Graphs'),
  (8, 'Mathematics', 16, 'c8-math-16', 'Playing with Numbers'),
  (8, 'Science', 1, 'c8-sci-01', 'Crop Production and Management'),
  (8, 'Science', 2, 'c8-sci-02', 'Microorganisms: Friend and Foe'),
  (8, 'Science', 3, 'c8-sci-03', 'Synthetic Fibres and Plastics'),
  (8, 'Science', 4, 'c8-sci-04', 'Materials: Metals and Non-Metals'),
  (8, 'Science', 5, 'c8-sci-05', 'Coal and Petroleum'),
  (8, 'Science', 6, 'c8-sci-06', 'Combustion and Flame'),
  (8, 'Science', 7, 'c8-sci-07', 'Conservation of Plants and Animals'),
  (8, 'Science', 8, 'c8-sci-08', 'Cell — Structure and Functions'),
  (8, 'Science', 9, 'c8-sci-09', 'Reproduction in Animals'),
  (8, 'Science', 10, 'c8-sci-10', 'Reaching the Age of Adolescence'),
  (8, 'Science', 11, 'c8-sci-11', 'Force and Pressure'),
  (8, 'Science', 12, 'c8-sci-12', 'Friction'),
  (8, 'Science', 13, 'c8-sci-13', 'Sound'),
  (8, 'Science', 14, 'c8-sci-14', 'Chemical Effects of Electric Current'),
  (8, 'Science', 15, 'c8-sci-15', 'Some Natural Phenomena'),
  (8, 'Science', 16, 'c8-sci-16', 'Light'),
  (8, 'Science', 17, 'c8-sci-17', 'Stars and the Solar System'),
  (8, 'Science', 18, 'c8-sci-18', 'Pollution of Air and Water'),
  (8, 'Social Science', 1, 'c8-sst-01', 'How, When and Where (History)'),
  (8, 'Social Science', 2, 'c8-sst-02', 'From Trade to Territory (History)'),
  (8, 'Social Science', 3, 'c8-sst-03', 'Ruling the Countryside (History)'),
  (8, 'Social Science', 4, 'c8-sst-04', 'Tribals, Dikus and the Vision of a Golden Age (History)'),
  (8, 'Social Science', 5, 'c8-sst-05', 'When People Rebel: 1857 and After (History)'),
  (8, 'Social Science', 6, 'c8-sst-06', 'Weavers, Iron Smelters and Factory Owners (History)'),
  (8, 'Social Science', 7, 'c8-sst-07', 'Civilising the “Native”, Educating the Nation (History)'),
  (8, 'Social Science', 8, 'c8-sst-08', 'Women, Caste and Reform (History)'),
  (8, 'Social Science', 9, 'c8-sst-09', 'The Making of the National Movement: 1870s–1947 (History)'),
  (8, 'Social Science', 10, 'c8-sst-10', 'India After Independence (History)'),
  (8, 'Social Science', 11, 'c8-sst-11', 'Resources (Geography)'),
  (8, 'Social Science', 12, 'c8-sst-12', 'Land, Soil, Water, Natural Vegetation and Wildlife Resources (Geography)'),
  (8, 'Social Science', 13, 'c8-sst-13', 'Mineral and Power Resources (Geography)'),
  (8, 'Social Science', 14, 'c8-sst-14', 'Agriculture (Geography)'),
  (8, 'Social Science', 15, 'c8-sst-15', 'Industries (Geography)'),
  (8, 'Social Science', 16, 'c8-sst-16', 'Human Resources (Geography)'),
  (8, 'Social Science', 17, 'c8-sst-17', 'The Indian Constitution (Civics)'),
  (8, 'Social Science', 18, 'c8-sst-18', 'Understanding Secularism (Civics)'),
  (8, 'Social Science', 19, 'c8-sst-19', 'Why do we need a Parliament? (Civics)'),
  (8, 'Social Science', 20, 'c8-sst-20', 'Understanding Laws (Civics)'),
  (8, 'Social Science', 21, 'c8-sst-21', 'Judiciary (Civics)'),
  (8, 'Social Science', 22, 'c8-sst-22', 'Understanding Our Criminal Justice System (Civics)'),
  (8, 'Social Science', 23, 'c8-sst-23', 'Understanding Marginalisation (Civics)'),
  (8, 'Social Science', 24, 'c8-sst-24', 'Confronting Marginalisation (Civics)'),
  (8, 'Social Science', 25, 'c8-sst-25', 'Public Facilities (Civics)'),
  (8, 'Social Science', 26, 'c8-sst-26', 'Law and Social Justice (Civics)')
on conflict (chapter_ref) do update set
  class_num = excluded.class_num,
  subject = excluded.subject,
  chapter_num = excluded.chapter_num,
  title = excluded.title;

insert into public.games_catalog (game_id, engine, subject, skill_tag, class_num, level, chapter_ref, name, icon, params, is_active) values
  ('c5-math-01-large-numbers', 'practice', 'Mathematics', 'c5-math-01-large-numbers', 5, 1, 'c5-math-01', 'Lakhs & Crores Stories', '🐟', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-02-angles', 'practice', 'Mathematics', 'c5-math-02-angles', 5, 1, 'c5-math-02', 'Angle Detective', '📐', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-03-area-compare', 'practice', 'Mathematics', 'c5-math-03-area-compare', 5, 1, 'c5-math-03', 'Same Area, Different Fence', '🟦', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-04-fractions', 'practice', 'Mathematics', 'c5-math-04-fractions', 5, 1, 'c5-math-04', 'Equivalent Fractions', '🍫', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-05-symmetry', 'practice', 'Mathematics', 'c5-math-05-symmetry', 5, 1, 'c5-math-05', 'Mirror Lines', '🪞', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-06-factors-multiples', 'practice', 'Mathematics', 'c5-math-06-factors-multiples', 5, 1, 'c5-math-06', 'Factors & Multiples', '✖️', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-07-patterns', 'practice', 'Mathematics', 'c5-math-07-patterns', 5, 1, 'c5-math-07', 'Number Patterns', '🔢', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-08-maps', 'practice', 'Mathematics', 'c5-math-08-maps', 5, 1, 'c5-math-08', 'Map Scale & Directions', '🗺️', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-09-nets', 'practice', 'Mathematics', 'c5-math-09-nets', 5, 1, 'c5-math-09', 'Nets of Solids', '📦', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-10-decimals', 'practice', 'Mathematics', 'c5-math-10-decimals', 5, 1, 'c5-math-10', 'Tenths & Hundredths', '🔟', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-11-perimeter-area', 'practice', 'Mathematics', 'c5-math-11-perimeter-area', 5, 1, 'c5-math-11', 'Fields & Fences', '🌾', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-12-charts', 'practice', 'Mathematics', 'c5-math-12-charts', 5, 1, 'c5-math-12', 'Read the Chart', '📊', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-13-mul-div', 'practice', 'Mathematics', 'c5-math-13-mul-div', 5, 1, 'c5-math-13', 'Multiply & Divide Stories', '🧮', '{"generator":"practice"}'::jsonb, true),
  ('c5-math-14-measure', 'practice', 'Mathematics', 'c5-math-14-measure', 5, 1, 'c5-math-14', 'Weight & Capacity', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-01-senses', 'practice', 'World Around Us', 'c5-wau-01-senses', 5, 1, 'c5-wau-01', 'Animal Super Senses', '🐜', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-02-snake-charmers', 'practice', 'World Around Us', 'c5-wau-02-snake-charmers', 5, 1, 'c5-wau-02', 'Kalbelia & Snakes', '🐍', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-03-digestion', 'practice', 'World Around Us', 'c5-wau-03-digestion', 5, 1, 'c5-wau-03', 'Journey of Food', '🍽️', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-04-food-spoil', 'practice', 'World Around Us', 'c5-wau-04-food-spoil', 5, 1, 'c5-wau-04', 'Why Food Spoils', '🥭', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-05-dispersal', 'practice', 'World Around Us', 'c5-wau-05-dispersal', 5, 1, 'c5-wau-05', 'How Seeds Travel', '🌱', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-06-water', 'practice', 'World Around Us', 'c5-wau-06-water', 5, 1, 'c5-wau-06', 'Every Drop Counts', '💧', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-07-float-sink', 'practice', 'World Around Us', 'c5-wau-07-float-sink', 5, 1, 'c5-wau-07', 'Float, Sink, Dissolve', '🧪', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-08-malaria', 'practice', 'World Around Us', 'c5-wau-08-malaria', 5, 1, 'c5-wau-08', 'Mosquitoes & Health', '🦟', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-09-mountains', 'practice', 'World Around Us', 'c5-wau-09-mountains', 5, 1, 'c5-wau-09', 'Climbing Together', '⛰️', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-10-forts', 'practice', 'World Around Us', 'c5-wau-10-forts', 5, 1, 'c5-wau-10', 'Fort Features', '🏰', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-11-space', 'practice', 'World Around Us', 'c5-wau-11-space', 5, 1, 'c5-wau-11', 'Life in Microgravity', '🚀', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-12-fuels', 'practice', 'World Around Us', 'c5-wau-12-fuels', 5, 1, 'c5-wau-12', 'Fuels that Finish', '⛽', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-13-changthang', 'practice', 'World Around Us', 'c5-wau-13-changthang', 5, 1, 'c5-wau-13', 'Life in Changthang', '🏔️', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-14-earthquake', 'practice', 'World Around Us', 'c5-wau-14-earthquake', 5, 1, 'c5-wau-14', 'When Earth Shakes', '🌍', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-15-breath', 'practice', 'World Around Us', 'c5-wau-15-breath', 5, 1, 'c5-wau-15', 'Hot Breath, Cold Breath', '🌬️', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-16-dignity', 'practice', 'World Around Us', 'c5-wau-16-dignity', 5, 1, 'c5-wau-16', 'Dignity of Work', '🧹', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-17-gender-sports', 'practice', 'World Around Us', 'c5-wau-17-gender-sports', 5, 1, 'c5-wau-17', 'Fair Play for All', '⚽', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-18-displacement', 'practice', 'World Around Us', 'c5-wau-18-displacement', 5, 1, 'c5-wau-18', 'When People Must Move', '🏠', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-19-farming', 'practice', 'World Around Us', 'c5-wau-19-farming', 5, 1, 'c5-wau-19', 'From Seed to Harvest', '🌾', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-20-forests', 'practice', 'World Around Us', 'c5-wau-20-forests', 5, 1, 'c5-wau-20', 'People of the Forest', '🌳', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-21-traits', 'practice', 'World Around Us', 'c5-wau-21-traits', 5, 1, 'c5-wau-21', 'Traits in a Family', '👨‍👧', '{"generator":"practice"}'::jsonb, true),
  ('c5-wau-22-migration', 'practice', 'World Around Us', 'c5-wau-22-migration', 5, 1, 'c5-wau-22', 'Seasonal Migration', '🚌', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-01-unit1', 'practice', 'English', 'c5-eng-01-unit1', 5, 1, 'c5-eng-01', 'Ice-cream & Kitchen Wisdom', '🍦', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-02-unit2', 'practice', 'English', 'c5-eng-02-unit2', 5, 1, 'c5-eng-02', 'Together We Fly', '🕊️', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-03-unit3', 'practice', 'English', 'c5-eng-03-unit3', 5, 1, 'c5-eng-03', 'Shadows & Survival', '🏝️', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-04-unit4', 'practice', 'English', 'c5-eng-04-unit4', 5, 1, 'c5-eng-04', 'Feelings & Family', '😢', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-05-unit5', 'practice', 'English', 'c5-eng-05-unit5', 5, 1, 'c5-eng-05', 'Rip Van Winkle', '😴', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-06-unit6', 'practice', 'English', 'c5-eng-06-unit6', 5, 1, 'c5-eng-06', 'Talking in Turn', '💬', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-07-unit7', 'practice', 'English', 'c5-eng-07-unit7', 5, 1, 'c5-eng-07', 'Upside-Down Worlds', '🙃', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-08-unit8', 'practice', 'English', 'c5-eng-08-unit8', 5, 1, 'c5-eng-08', 'Friendship & Kindness', '🤝', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-09-unit9', 'practice', 'English', 'c5-eng-09-unit9', 5, 1, 'c5-eng-09', 'People on the Move', '🌍', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-10-unit10', 'practice', 'English', 'c5-eng-10-unit10', 5, 1, 'c5-eng-10', 'Brave Hearts', '🐻', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-11-comprehension', 'practice', 'English', 'c5-eng-11-comprehension', 5, 1, 'c5-eng-11', 'Read & Infer', '📖', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-12-grammar', 'practice', 'English', 'c5-eng-12-grammar', 5, 1, 'c5-eng-12', 'Tenses & Agreement', '✍️', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-13-vocabulary', 'practice', 'English', 'c5-eng-13-vocabulary', 5, 1, 'c5-eng-13', 'Word Relationships', '🔤', '{"generator":"practice"}'::jsonb, true),
  ('c5-eng-14-writing', 'practice', 'English', 'c5-eng-14-writing', 5, 1, 'c5-eng-14', 'Diary, Letter, Notice', '📝', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-01-numbers', 'practice', 'Mathematics', 'c6-math-01-numbers', 6, 1, 'c6-math-01', 'Rounding & Roman Numerals', '🔢', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-02-whole', 'practice', 'Mathematics', 'c6-math-02-whole', 6, 1, 'c6-math-02', 'Whole Number Properties', '➕', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-03-hcf-lcm', 'practice', 'Mathematics', 'c6-math-03-hcf-lcm', 6, 1, 'c6-math-03', 'Divisibility, HCF & LCM', '🧩', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-04-geometry', 'practice', 'Mathematics', 'c6-math-04-geometry', 6, 1, 'c6-math-04', 'Points, Lines & Shapes', '📏', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-05-shapes', 'practice', 'Mathematics', 'c6-math-05-shapes', 6, 1, 'c6-math-05', 'Classify Shapes', '🔺', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-06-integers', 'practice', 'Mathematics', 'c6-math-06-integers', 6, 1, 'c6-math-06', 'Positive & Negative', '➖', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-07-fractions', 'practice', 'Mathematics', 'c6-math-07-fractions', 6, 1, 'c6-math-07', 'Unlike Denominators', '🍕', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-08-decimals', 'practice', 'Mathematics', 'c6-math-08-decimals', 6, 1, 'c6-math-08', 'Compare Decimals', '🔟', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-09-data', 'practice', 'Mathematics', 'c6-math-09-data', 6, 1, 'c6-math-09', 'Pictographs & Bar Graphs', '📊', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-10-mensuration', 'practice', 'Mathematics', 'c6-math-10-mensuration', 6, 1, 'c6-math-10', 'Perimeter & Area', '📐', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-11-algebra', 'practice', 'Mathematics', 'c6-math-11-algebra', 6, 1, 'c6-math-11', 'Letters for Numbers', '𝑥', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-12-ratio', 'practice', 'Mathematics', 'c6-math-12-ratio', 6, 1, 'c6-math-12', 'Ratio & Proportion', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-13-symmetry', 'practice', 'Mathematics', 'c6-math-13-symmetry', 6, 1, 'c6-math-13', 'Lines of Symmetry', '🦋', '{"generator":"practice"}'::jsonb, true),
  ('c6-math-14-constructions', 'practice', 'Mathematics', 'c6-math-14-constructions', 6, 1, 'c6-math-14', 'Constructions', '✏️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-01-nutrients', 'practice', 'Science', 'c6-sci-01-nutrients', 6, 1, 'c6-sci-01', 'Nutrients & Tests', '🥗', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-02-materials', 'practice', 'Science', 'c6-sci-02-materials', 6, 1, 'c6-sci-02', 'Sort the Materials', '📦', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-03-separation', 'practice', 'Science', 'c6-sci-03-separation', 6, 1, 'c6-sci-03', 'Choose the Method', '🌾', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-04-plants', 'practice', 'Science', 'c6-sci-04-plants', 6, 1, 'c6-sci-04', 'Herbs, Shrubs & Roots', '🌿', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-05-joints', 'practice', 'Science', 'c6-sci-05-joints', 6, 1, 'c6-sci-05', 'Bones & Joints', '🦴', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-06-motion', 'practice', 'Science', 'c6-sci-06-motion', 6, 1, 'c6-sci-06', 'Motion & SI Units', '📏', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-07-habitat', 'practice', 'Science', 'c6-sci-07-habitat', 6, 1, 'c6-sci-07', 'Living Things & Habitats', '🦎', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-08-water-cycle', 'practice', 'Science', 'c6-sci-08-water-cycle', 6, 1, 'c6-sci-08', 'Water Cycle & Drought', '💧', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-09-light', 'practice', 'Science', 'c6-sci-09-light', 6, 1, 'c6-sci-09', 'Light & Shadows', '💡', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-10-circuits', 'practice', 'Science', 'c6-sci-10-circuits', 6, 1, 'c6-sci-10', 'Will the Bulb Glow?', '🔋', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-11-magnets', 'practice', 'Science', 'c6-sci-11-magnets', 6, 1, 'c6-sci-11', 'Poles & Attraction', '🧲', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-12-air', 'practice', 'Science', 'c6-sci-12-air', 6, 1, 'c6-sci-12', 'What’s in Air?', '🌬️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sci-13-waste', 'practice', 'Science', 'c6-sci-13-waste', 6, 1, 'c6-sci-13', 'Waste Wise', '♻️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-01-sources', 'practice', 'Social Science', 'c6-sst-01-sources', 6, 1, 'c6-sst-01', 'Manuscripts & Inscriptions', '📜', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-02-farming', 'practice', 'Social Science', 'c6-sst-02-farming', 6, 1, 'c6-sst-02', 'First Farmers', '🌾', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-03-harappa', 'practice', 'Social Science', 'c6-sst-03-harappa', 6, 1, 'c6-sst-03', 'Harappan Cities', '🏙️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-04-vedas', 'practice', 'Social Science', 'c6-sst-04-vedas', 6, 1, 'c6-sst-04', 'Vedas & Burials', '📖', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-05-mahajanapadas', 'practice', 'Social Science', 'c6-sst-05-mahajanapadas', 6, 1, 'c6-sst-05', 'Janapadas & Magadha', '👑', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-06-buddha', 'practice', 'Social Science', 'c6-sst-06-buddha', 6, 1, 'c6-sst-06', 'Buddha & Mahavira', '☸️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-07-ashoka', 'practice', 'Social Science', 'c6-sst-07-ashoka', 6, 1, 'c6-sst-07', 'Ashoka After Kalinga', '🦁', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-08-towns', 'practice', 'Social Science', 'c6-sst-08-towns', 6, 1, 'c6-sst-08', 'Iron, Crafts & Towns', '🏺', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-09-silk', 'practice', 'Social Science', 'c6-sst-09-silk', 6, 1, 'c6-sst-09', 'Silk Route & Bhakti', '🧵', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-10-gupta', 'practice', 'Social Science', 'c6-sst-10-gupta', 6, 1, 'c6-sst-10', 'Guptas & Assemblies', '🏛️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-11-art', 'practice', 'Social Science', 'c6-sst-11-art', 6, 1, 'c6-sst-11', 'Stupas, Temples & Books', '🛕', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-12-solar', 'practice', 'Social Science', 'c6-sst-12-solar', 6, 1, 'c6-sst-12', 'Planets & Stars', '🪐', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-13-globe', 'practice', 'Social Science', 'c6-sst-13-globe', 6, 1, 'c6-sst-13', 'Latitudes & Longitudes', '🌐', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-14-motions', 'practice', 'Social Science', 'c6-sst-14-motions', 6, 1, 'c6-sst-14', 'Rotation & Revolution', '🌍', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-15-maps', 'practice', 'Social Science', 'c6-sst-15-maps', 6, 1, 'c6-sst-15', 'Sketch, Plan & Scale', '🗺️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-16-domains', 'practice', 'Social Science', 'c6-sst-16-domains', 6, 1, 'c6-sst-16', 'Lithosphere to Biosphere', '🌏', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-17-landforms', 'practice', 'Social Science', 'c6-sst-17-landforms', 6, 1, 'c6-sst-17', 'Mountains, Plateaus, Plains', '⛰️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-18-india', 'practice', 'Social Science', 'c6-sst-18-india', 6, 1, 'c6-sst-18', 'India: Location & Neighbours', '🇮🇳', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-19-climate', 'practice', 'Social Science', 'c6-sst-19-climate', 6, 1, 'c6-sst-19', 'Seasons & Wildlife', '🐅', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-20-diversity', 'practice', 'Social Science', 'c6-sst-20-diversity', 6, 1, 'c6-sst-20', 'Unity in Diversity', '🪔', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-21-discrimination', 'practice', 'Social Science', 'c6-sst-21-discrimination', 6, 1, 'c6-sst-21', 'Prejudice & Inequality', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-22-government', 'practice', 'Social Science', 'c6-sst-22-government', 6, 1, 'c6-sst-22', 'Why We Need Government', '🏛️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-23-democracy', 'practice', 'Social Science', 'c6-sst-23-democracy', 6, 1, 'c6-sst-23', 'How Democracy Works', '🗳️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-24-panchayat', 'practice', 'Social Science', 'c6-sst-24-panchayat', 6, 1, 'c6-sst-24', 'Village Government', '🏘️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-25-rural-admin', 'practice', 'Social Science', 'c6-sst-25-rural-admin', 6, 1, 'c6-sst-25', 'Police Station & Patwari', '👮', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-26-urban', 'practice', 'Social Science', 'c6-sst-26-urban', 6, 1, 'c6-sst-26', 'Municipal Work', '🏙️', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-27-rural-work', 'practice', 'Social Science', 'c6-sst-27-rural-work', 6, 1, 'c6-sst-27', 'Farm & Non-farm Work', '🚜', '{"generator":"practice"}'::jsonb, true),
  ('c6-sst-28-urban-work', 'practice', 'Social Science', 'c6-sst-28-urban-work', 6, 1, 'c6-sst-28', 'Work in the City', '🛠️', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-01-patrick', 'practice', 'English', 'c6-eng-01-patrick', 6, 1, 'c6-eng-01', 'Patrick''s Homework', '📚', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-02-dog', 'practice', 'English', 'c6-eng-02-dog', 6, 1, 'c6-eng-02', 'A New Master', '🐕', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-03-taro', 'practice', 'English', 'c6-eng-03-taro', 6, 1, 'c6-eng-03', 'Taro''s Reward', '🍶', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-04-kalpana', 'practice', 'English', 'c6-eng-04-kalpana', 6, 1, 'c6-eng-04', 'Kalpana Chawla', '🚀', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-05-school', 'practice', 'English', 'c6-eng-05-school', 6, 1, 'c6-eng-05', 'Miss Beam’s School', '🏫', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-06-who', 'practice', 'English', 'c6-eng-06-who', 6, 1, 'c6-eng-06', 'Who I Am', '🧒', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-07-fair', 'practice', 'English', 'c6-eng-07-fair', 6, 1, 'c6-eng-07', 'Fair Play', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-08-fairground', 'practice', 'English', 'c6-eng-08-fairground', 6, 1, 'c6-eng-08', 'The Lucky Shop', '🎡', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-09-desert', 'practice', 'English', 'c6-eng-09-desert', 6, 1, 'c6-eng-09', 'Desert Survivors', '🐪', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-10-banyan', 'practice', 'English', 'c6-eng-10-banyan', 6, 1, 'c6-eng-10', 'The Banyan Tree', '🌳', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-11-grammar', 'practice', 'English', 'c6-eng-11-grammar', 6, 1, 'c6-eng-11', 'Articles, Tenses, Prepositions', '✍️', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-12-comprehension', 'practice', 'English', 'c6-eng-12-comprehension', 6, 1, 'c6-eng-12', 'Unseen Passage', '📖', '{"generator":"practice"}'::jsonb, true),
  ('c6-eng-13-writing', 'practice', 'English', 'c6-eng-13-writing', 6, 1, 'c6-eng-13', 'Notice & Diary', '📝', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-01-integers', 'practice', 'Mathematics', 'c7-math-01-integers', 7, 1, 'c7-math-01', 'Integer Stories', '🌡️', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-02-frac-dec', 'practice', 'Mathematics', 'c7-math-02-frac-dec', 7, 1, 'c7-math-02', 'Fractions × Decimals', '➗', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-03-data', 'practice', 'Mathematics', 'c7-math-03-data', 7, 1, 'c7-math-03', 'Mean, Mode, Bar Graphs', '📊', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-04-equations', 'practice', 'Mathematics', 'c7-math-04-equations', 7, 1, 'c7-math-04', 'Solve for the Unknown', '𝑥', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-05-lines', 'practice', 'Mathematics', 'c7-math-05-lines', 7, 1, 'c7-math-05', 'Parallel Lines & Transversals', '📐', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-06-triangles', 'practice', 'Mathematics', 'c7-math-06-triangles', 7, 1, 'c7-math-06', 'Triangle Angle Sum', '🔺', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-07-congruence', 'practice', 'Mathematics', 'c7-math-07-congruence', 7, 1, 'c7-math-07', 'SSS, SAS, ASA, RHS', '≅', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-08-percent', 'practice', 'Mathematics', 'c7-math-08-percent', 7, 1, 'c7-math-08', 'Profit, Loss & Interest', '💰', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-09-rationals', 'practice', 'Mathematics', 'c7-math-09-rationals', 7, 1, 'c7-math-09', 'Rational Numbers', 'ℚ', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-10-construct', 'practice', 'Mathematics', 'c7-math-10-construct', 7, 1, 'c7-math-10', 'Construct Triangles', '✏️', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-11-circles', 'practice', 'Mathematics', 'c7-math-11-circles', 7, 1, 'c7-math-11', 'Circles & Paths', '⭕', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-12-algebra', 'practice', 'Mathematics', 'c7-math-12-algebra', 7, 1, 'c7-math-12', 'Terms & Like Terms', '🔣', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-13-exponents', 'practice', 'Mathematics', 'c7-math-13-exponents', 7, 1, 'c7-math-13', 'Laws of Exponents', '⚡', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-14-symmetry', 'practice', 'Mathematics', 'c7-math-14-symmetry', 7, 1, 'c7-math-14', 'Rotational Symmetry', '🔄', '{"generator":"practice"}'::jsonb, true),
  ('c7-math-15-solids', 'practice', 'Mathematics', 'c7-math-15-solids', 7, 1, 'c7-math-15', 'Views & Nets', '📦', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-01-plants-food', 'practice', 'Science', 'c7-sci-01-plants-food', 7, 1, 'c7-sci-01', 'Modes of Nutrition', '🌱', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-02-animals-food', 'practice', 'Science', 'c7-sci-02-animals-food', 7, 1, 'c7-sci-02', 'From Ingestion to Egestion', '🦷', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-03-fibre', 'practice', 'Science', 'c7-sci-03-fibre', 7, 1, 'c7-sci-03', 'Wool & Silk', '🐑', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-04-heat', 'practice', 'Science', 'c7-sci-04-heat', 7, 1, 'c7-sci-04', 'Heat & Temperature', '🌡️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-05-acids', 'practice', 'Science', 'c7-sci-05-acids', 7, 1, 'c7-sci-05', 'Indicators & Neutralisation', '🧪', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-06-changes', 'practice', 'Science', 'c7-sci-06-changes', 7, 1, 'c7-sci-06', 'Physical or Chemical?', '🔥', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-07-climate', 'practice', 'Science', 'c7-sci-07-climate', 7, 1, 'c7-sci-07', 'Climate & Adaptations', '🐧', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-08-winds', 'practice', 'Science', 'c7-sci-08-winds', 7, 1, 'c7-sci-08', 'Air Pressure & Cyclones', '🌀', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-09-soil', 'practice', 'Science', 'c7-sci-09-soil', 7, 1, 'c7-sci-09', 'Soil Horizons & Types', '🧱', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-10-respiration', 'practice', 'Science', 'c7-sci-10-respiration', 7, 1, 'c7-sci-10', 'Breathing & Energy', '🫁', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-11-transport', 'practice', 'Science', 'c7-sci-11-transport', 7, 1, 'c7-sci-11', 'Blood, Heart & Xylem', '❤️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-12-repro-plants', 'practice', 'Science', 'c7-sci-12-repro-plants', 7, 1, 'c7-sci-12', 'Seeds & Vegetative Parts', '🌸', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-13-speed', 'practice', 'Science', 'c7-sci-13-speed', 7, 1, 'c7-sci-13', 'Speed, Distance, Time', '🚂', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-14-current', 'practice', 'Science', 'c7-sci-14-current', 7, 1, 'c7-sci-14', 'Heating & Magnetic Effects', '⚡', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-15-light', 'practice', 'Science', 'c7-sci-15-light', 7, 1, 'c7-sci-15', 'Mirrors & Lenses', '🪞', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-16-water', 'practice', 'Science', 'c7-sci-16-water', 7, 1, 'c7-sci-16', 'Groundwater & Scarcity', '💧', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-17-forests', 'practice', 'Science', 'c7-sci-17-forests', 7, 1, 'c7-sci-17', 'Forest Web of Life', '🌲', '{"generator":"practice"}'::jsonb, true),
  ('c7-sci-18-sewage', 'practice', 'Science', 'c7-sci-18-sewage', 7, 1, 'c7-sci-18', 'Cleaning Wastewater', '🚰', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-01-thousand', 'practice', 'Social Science', 'c7-sst-01-thousand', 7, 1, 'c7-sst-01', 'Maps, Manuscripts, Terms', '📜', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-02-kings', 'practice', 'Social Science', 'c7-sst-02-kings', 7, 1, 'c7-sst-02', 'Cholas & New Dynasties', '👑', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-03-sultanate', 'practice', 'Social Science', 'c7-sst-03-sultanate', 7, 1, 'c7-sst-03', 'Delhi Sultanate', '🕌', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-04-mughals', 'practice', 'Social Science', 'c7-sst-04-mughals', 7, 1, 'c7-sst-04', 'Mughal Administration', '🦁', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-05-buildings', 'practice', 'Social Science', 'c7-sst-05-buildings', 7, 1, 'c7-sst-05', 'Temples, Mosques, Gardens', '🕌', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-06-traders', 'practice', 'Social Science', 'c7-sst-06-traders', 7, 1, 'c7-sst-06', 'Temple Towns & Ports', '⚓', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-07-tribes', 'practice', 'Social Science', 'c7-sst-07-tribes', 7, 1, 'c7-sst-07', 'Tribes & Nomads', '🏕️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-08-bhakti', 'practice', 'Social Science', 'c7-sst-08-bhakti', 7, 1, 'c7-sst-08', 'Bhakti & Sufi Saints', '🙏', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-09-regions', 'practice', 'Social Science', 'c7-sst-09-regions', 7, 1, 'c7-sst-09', 'Language, Dance, Faith', '🎭', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-10-18c', 'practice', 'Social Science', 'c7-sst-10-18c', 7, 1, 'c7-sst-10', 'After the Mughals', '⚔️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-11-environment', 'practice', 'Social Science', 'c7-sst-11-environment', 7, 1, 'c7-sst-11', 'Natural & Human Environment', '🌿', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-12-earth', 'practice', 'Social Science', 'c7-sst-12-earth', 7, 1, 'c7-sst-12', 'Rocks & Layers', '🪨', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-13-changing', 'practice', 'Social Science', 'c7-sst-13-changing', 7, 1, 'c7-sst-13', 'Earthquakes & Landforms', '🌋', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-14-air', 'practice', 'Social Science', 'c7-sst-14-air', 7, 1, 'c7-sst-14', 'Atmosphere & Weather', '💨', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-15-water-geo', 'practice', 'Social Science', 'c7-sst-15-water-geo', 7, 1, 'c7-sst-15', 'Oceans & Tides', '🌊', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-16-vegetation', 'practice', 'Social Science', 'c7-sst-16-vegetation', 7, 1, 'c7-sst-16', 'Forests & Animals', '🦁', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-17-settlement', 'practice', 'Social Science', 'c7-sst-17-settlement', 7, 1, 'c7-sst-17', 'Where and How We Live', '🏘️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-18-amazon-ganges', 'practice', 'Social Science', 'c7-sst-18-amazon-ganges', 7, 1, 'c7-sst-18', 'Amazon & Ganga-Brahmaputra', '🏞️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-19-deserts', 'practice', 'Social Science', 'c7-sst-19-deserts', 7, 1, 'c7-sst-19', 'Sahara & Ladakh', '🏜️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-20-equality', 'practice', 'Social Science', 'c7-sst-20-equality', 7, 1, 'c7-sst-20', 'Equality in Democracy', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-21-health', 'practice', 'Social Science', 'c7-sst-21-health', 7, 1, 'c7-sst-21', 'Public & Private Health', '🏥', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-22-state-gov', 'practice', 'Social Science', 'c7-sst-22-state-gov', 7, 1, 'c7-sst-22', 'MLA, CM & Lists', '🏛️', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-23-gender', 'practice', 'Social Science', 'c7-sst-23-gender', 7, 1, 'c7-sst-23', 'Gendered Lives', '👧', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-24-women', 'practice', 'Social Science', 'c7-sst-24-women', 7, 1, 'c7-sst-24', 'Education & Women’s Work', '👩‍🎓', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-25-media', 'practice', 'Social Science', 'c7-sst-25-media', 7, 1, 'c7-sst-25', 'News, Ads & Bias', '📺', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-26-markets', 'practice', 'Social Science', 'c7-sst-26-markets', 7, 1, 'c7-sst-26', 'Weekly, Neighbourhood, Mall', '🛒', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-27-shirt', 'practice', 'Social Science', 'c7-sst-27-shirt', 7, 1, 'c7-sst-27', 'Who Made the Shirt?', '👕', '{"generator":"practice"}'::jsonb, true),
  ('c7-sst-28-struggles', 'practice', 'Social Science', 'c7-sst-28-struggles', 7, 1, 'c7-sst-28', 'People Who Fought Back', '✊', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-01-three-q', 'practice', 'English', 'c7-eng-01-three-q', 7, 1, 'c7-eng-01', 'The King’s Three Questions', '👑', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-02-chappals', 'practice', 'English', 'c7-eng-02-chappals', 7, 1, 'c7-eng-02', 'A Gift of Chappals', '👡', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-03-hilsa', 'practice', 'English', 'c7-eng-03-hilsa', 7, 1, 'c7-eng-03', 'Gopal and the Hilsa', '🐟', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-04-ashes', 'practice', 'English', 'c7-eng-04-ashes', 7, 1, 'c7-eng-04', 'The Honest Farmer', '🌼', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-05-quality', 'practice', 'English', 'c7-eng-05-quality', 7, 1, 'c7-eng-05', 'The Shoemaker’s Quality', '👞', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-06-detectives', 'practice', 'English', 'c7-eng-06-detectives', 7, 1, 'c7-eng-06', 'Maya and Nishad', '🔍', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-07-vita', 'practice', 'English', 'c7-eng-07-vita', 7, 1, 'c7-eng-07', 'Vita-Wonk', '🧪', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-08-fire', 'practice', 'English', 'c7-eng-08-fire', 7, 1, 'c7-eng-08', 'Fire: Friend and Foe', '🔥', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-09-bicycle', 'practice', 'English', 'c7-eng-09-bicycle', 7, 1, 'c7-eng-09', 'The Helpful Friend', '🚲', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-10-cricket', 'practice', 'English', 'c7-eng-10-cricket', 7, 1, 'c7-eng-10', 'How Cricket Grew', '🏏', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-11-grammar', 'practice', 'English', 'c7-eng-11-grammar', 7, 1, 'c7-eng-11', 'Voice & Clauses', '✍️', '{"generator":"practice"}'::jsonb, true),
  ('c7-eng-12-comprehension', 'practice', 'English', 'c7-eng-12-comprehension', 7, 1, 'c7-eng-12', 'Thematic Unseen Passage', '📖', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-01-rationals', 'practice', 'Mathematics', 'c8-math-01-rationals', 8, 1, 'c8-math-01', 'Properties of Rationals', 'ℚ', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-02-linear', 'practice', 'Mathematics', 'c8-math-02-linear', 8, 1, 'c8-math-02', 'Age & Digit Equations', '𝑥', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-03-quads', 'practice', 'Mathematics', 'c8-math-03-quads', 8, 1, 'c8-math-03', 'Parallelograms & Polygons', '▱', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-04-construct', 'practice', 'Mathematics', 'c8-math-04-construct', 8, 1, 'c8-math-04', 'Construct Quadrilaterals', '✏️', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-05-data', 'practice', 'Mathematics', 'c8-math-05-data', 8, 1, 'c8-math-05', 'Pie Charts & Probability', '📊', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-06-squares', 'practice', 'Mathematics', 'c8-math-06-squares', 8, 1, 'c8-math-06', 'Squares & Roots', '²', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-07-cubes', 'practice', 'Mathematics', 'c8-math-07-cubes', 8, 1, 'c8-math-07', 'Cubes & Cube Roots', '³', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-08-compound', 'practice', 'Mathematics', 'c8-math-08-compound', 8, 1, 'c8-math-08', 'Compound Interest & Discount', '💹', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-09-identities', 'practice', 'Mathematics', 'c8-math-09-identities', 8, 1, 'c8-math-09', 'Identities', '🔣', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-10-views', 'practice', 'Mathematics', 'c8-math-10-views', 8, 1, 'c8-math-10', 'Views of Solids', '📦', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-11-mensuration', 'practice', 'Mathematics', 'c8-math-11-mensuration', 8, 1, 'c8-math-11', 'Surface Area & Volume', '🛢️', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-12-exponents', 'practice', 'Mathematics', 'c8-math-12-exponents', 8, 1, 'c8-math-12', 'Standard Form', '🔬', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-13-proportion', 'practice', 'Mathematics', 'c8-math-13-proportion', 8, 1, 'c8-math-13', 'Work & Speed', '👷', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-14-factor', 'practice', 'Mathematics', 'c8-math-14-factor', 8, 1, 'c8-math-14', 'Factorise Completely', '🧩', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-15-graphs', 'practice', 'Mathematics', 'c8-math-15-graphs', 8, 1, 'c8-math-15', 'Plot & Read Graphs', '📈', '{"generator":"practice"}'::jsonb, true),
  ('c8-math-16-divisibility', 'practice', 'Mathematics', 'c8-math-16-divisibility', 8, 1, 'c8-math-16', 'Letters for Digits', '🔢', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-01-crops', 'practice', 'Science', 'c8-sci-01-crops', 8, 1, 'c8-sci-01', 'From Soil to Store', '🌾', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-02-microbes', 'practice', 'Science', 'c8-sci-02-microbes', 8, 1, 'c8-sci-02', 'Friends & Foes', '🦠', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-03-plastics', 'practice', 'Science', 'c8-sci-03-plastics', 8, 1, 'c8-sci-03', 'Nylon, Polyester, Plastic', '🧵', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-04-metals', 'practice', 'Science', 'c8-sci-04-metals', 8, 1, 'c8-sci-04', 'Metal or Non-metal?', '⚙️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-05-fossil', 'practice', 'Science', 'c8-sci-05-fossil', 8, 1, 'c8-sci-05', 'Exhaustible Fuels', '⛽', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-06-flame', 'practice', 'Science', 'c8-sci-06-flame', 8, 1, 'c8-sci-06', 'Fire Triangle & Zones', '🔥', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-07-conserve', 'practice', 'Science', 'c8-sci-07-conserve', 8, 1, 'c8-sci-07', 'Biodiversity & Forests', '🐼', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-08-cell', 'practice', 'Science', 'c8-sci-08-cell', 8, 1, 'c8-sci-08', 'The Unit of Life', '🔬', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-09-repro-animals', 'practice', 'Science', 'c8-sci-09-repro-animals', 8, 1, 'c8-sci-09', 'Eggs & Birth', '🥚', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-10-adolescence', 'practice', 'Science', 'c8-sci-10-adolescence', 8, 1, 'c8-sci-10', 'Hormones & Growing Up', '🧑', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-11-force', 'practice', 'Science', 'c8-sci-11-force', 8, 1, 'c8-sci-11', 'Contact & Non-contact Forces', '💪', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-12-friction', 'practice', 'Science', 'c8-sci-12-friction', 8, 1, 'c8-sci-12', 'Static, Sliding, Rolling', '🛞', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-13-sound', 'practice', 'Science', 'c8-sci-13-sound', 8, 1, 'c8-sci-13', 'Frequency & Pitch', '🔊', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-14-electrolysis', 'practice', 'Science', 'c8-sci-14-electrolysis', 8, 1, 'c8-sci-14', 'Electroplating', '⚡', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-15-lightning', 'practice', 'Science', 'c8-sci-15-lightning', 8, 1, 'c8-sci-15', 'Lightning & Earthquakes', '⚡', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-16-light', 'practice', 'Science', 'c8-sci-16-light', 8, 1, 'c8-sci-16', 'Laws of Reflection & Eyes', '👁️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-17-sky', 'practice', 'Science', 'c8-sci-17-sky', 8, 1, 'c8-sci-17', 'Moon, Planets, Constellations', '🌙', '{"generator":"practice"}'::jsonb, true),
  ('c8-sci-18-pollution', 'practice', 'Science', 'c8-sci-18-pollution', 8, 1, 'c8-sci-18', 'Clean Air, Clean Water', '🏭', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-01-how-when', 'practice', 'Social Science', 'c8-sst-01-how-when', 8, 1, 'c8-sst-01', 'Colonial Records', '📁', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-02-trade', 'practice', 'Social Science', 'c8-sst-02-trade', 8, 1, 'c8-sst-02', 'Company to Power', '⛵', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-03-countryside', 'practice', 'Social Science', 'c8-sst-03-countryside', 8, 1, 'c8-sst-03', 'Revenue & Indigo', '🌿', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-04-tribals', 'practice', 'Social Science', 'c8-sst-04-tribals', 8, 1, 'c8-sst-04', 'Birsa Munda', '🌲', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-05-1857', 'practice', 'Social Science', 'c8-sst-05-1857', 8, 1, 'c8-sst-05', 'The 1857 Uprising', '⚔️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-06-weavers', 'practice', 'Social Science', 'c8-sst-06-weavers', 8, 1, 'c8-sst-06', 'Crafts under Colonial Rule', '🧵', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-07-education', 'practice', 'Social Science', 'c8-sst-07-education', 8, 1, 'c8-sst-07', 'Macaulay vs Orientalists', '🏫', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-08-reform', 'practice', 'Social Science', 'c8-sst-08-reform', 8, 1, 'c8-sst-08', 'Social Reformers', '✊', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-09-national', 'practice', 'Social Science', 'c8-sst-09-national', 8, 1, 'c8-sst-09', 'From Congress to Freedom', '🇮🇳', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-10-after-1947', 'practice', 'Social Science', 'c8-sst-10-after-1947', 8, 1, 'c8-sst-10', 'A New Nation', '📜', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-11-resources', 'practice', 'Social Science', 'c8-sst-11-resources', 8, 1, 'c8-sst-11', 'Types of Resources', '💎', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-12-land-soil', 'practice', 'Social Science', 'c8-sst-12-land-soil', 8, 1, 'c8-sst-12', 'Conserve Soil & Water', '🌍', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-13-minerals', 'practice', 'Social Science', 'c8-sst-13-minerals', 8, 1, 'c8-sst-13', 'Ores & Energy', '⛏️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-14-agriculture', 'practice', 'Social Science', 'c8-sst-14-agriculture', 8, 1, 'c8-sst-14', 'Types of Farming', '🚜', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-15-industries', 'practice', 'Social Science', 'c8-sst-15-industries', 8, 1, 'c8-sst-15', 'Agro, Mineral, Information', '🏭', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-16-human-res', 'practice', 'Social Science', 'c8-sst-16-human-res', 8, 1, 'c8-sst-16', 'People as a Resource', '👥', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-17-constitution', 'practice', 'Social Science', 'c8-sst-17-constitution', 8, 1, 'c8-sst-17', 'Key Features', '📜', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-18-secularism', 'practice', 'Social Science', 'c8-sst-18-secularism', 8, 1, 'c8-sst-18', 'Indian Secularism', '🕊️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-19-parliament', 'practice', 'Social Science', 'c8-sst-19-parliament', 8, 1, 'c8-sst-19', 'Lok Sabha & Rajya Sabha', '🏛️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-20-laws', 'practice', 'Social Science', 'c8-sst-20-laws', 8, 1, 'c8-sst-20', 'Who Makes Laws?', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-21-judiciary', 'practice', 'Social Science', 'c8-sst-21-judiciary', 8, 1, 'c8-sst-21', 'Independent Courts', '👨‍⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-22-cjs', 'practice', 'Social Science', 'c8-sst-22-cjs', 8, 1, 'c8-sst-22', 'FIR, Police, Fair Trial', '👮', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-23-margin', 'practice', 'Social Science', 'c8-sst-23-margin', 8, 1, 'c8-sst-23', 'Adivasis, Minorities, Dalits', '🗣️', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-24-confront', 'practice', 'Social Science', 'c8-sst-24-confront', 8, 1, 'c8-sst-24', 'Laws & Struggles', '📜', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-25-facilities', 'practice', 'Social Science', 'c8-sst-25-facilities', 8, 1, 'c8-sst-25', 'Water as a Right', '🚰', '{"generator":"practice"}'::jsonb, true),
  ('c8-sst-26-bhopal', 'practice', 'Social Science', 'c8-sst-26-bhopal', 8, 1, 'c8-sst-26', 'Bhopal & Worker Safety', '⚖️', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-01-christmas', 'practice', 'English', 'c8-eng-01-christmas', 8, 1, 'c8-eng-01', 'A Letter from the Trenches', '✉️', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-02-tsunami', 'practice', 'English', 'c8-eng-02-tsunami', 8, 1, 'c8-eng-02', 'When the Sea Rose', '🌊', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-03-glimpses', 'practice', 'English', 'c8-eng-03-glimpses', 8, 1, 'c8-eng-03', 'Comics of 1757–1857', '📰', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-04-bepin', 'practice', 'English', 'c8-eng-04-bepin', 8, 1, 'c8-eng-04', 'A Lapse of Memory', '🤔', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-05-summit', 'practice', 'English', 'c8-eng-05-summit', 8, 1, 'c8-eng-05', 'Everest & Inner Peaks', '🏔️', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-06-fawn', 'practice', 'English', 'c8-eng-06-fawn', 8, 1, 'c8-eng-06', 'Jody’s Fawn', '🦌', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-07-cambridge', 'practice', 'English', 'c8-eng-07-cambridge', 8, 1, 'c8-eng-07', 'Hawking & Firdaus', '♿', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-08-monsoon', 'practice', 'English', 'c8-eng-08-monsoon', 8, 1, 'c8-eng-08', 'Ruskin Bond’s Diary', '🌧️', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-09-stone-face', 'practice', 'English', 'c8-eng-09-stone-face', 8, 1, 'c8-eng-09', 'The Great Stone Face', '🗿', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-10-grammar', 'practice', 'English', 'c8-eng-10-grammar', 8, 1, 'c8-eng-10', 'Reported Speech & If-clauses', '✍️', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-11-analytical', 'practice', 'English', 'c8-eng-11-analytical', 8, 1, 'c8-eng-11', 'HOTS Unseen Passage', '📖', '{"generator":"practice"}'::jsonb, true),
  ('c8-eng-12-writing', 'practice', 'English', 'c8-eng-12-writing', 8, 1, 'c8-eng-12', 'Letter to the Editor & Speech', '📰', '{"generator":"practice"}'::jsonb, true)
on conflict (game_id) do update set
  engine = excluded.engine,
  subject = excluded.subject,
  skill_tag = excluded.skill_tag,
  class_num = excluded.class_num,
  level = excluded.level,
  chapter_ref = excluded.chapter_ref,
  name = excluded.name,
  icon = excluded.icon,
  params = excluded.params,
  is_active = excluded.is_active;
